config/routes.rb
ClubBiz::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :students do
    member do
      get :clubs
      get :events
      get :messages
    end
  end
  resources :admins do
    member do
      get :events
      get :details
      get :groups
    end
  end
  resources :clubs
  resources :student_clubs, only: [:create, :destroy]
  resources :events do
    member do
      get :club
      get :ads
      get :announcements
      get :new_reservation
      get :sales
    end
  end
  resources :ticket_reservations, only: :create
  resources :posts, only: :create
  resources :ads, only: :create
  resources :announcements, only: :create
  resources :messages, only: :create
  resources :registered_clubs do
    member do
      get :officers
    end
  end
  resources :officers, only: :create
  resources :verifications, only: [:new, :create, :update]
  resources :admin_details, only: :create

  root 'static_pages#home'
  match '/signup',  to: 'students#new',         via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get 'search_events' => 'events#index'
  get 'search_clubs' => 'clubs#index'
  

end

app/models/club.rb
# stores details for a club profile
# club cannot exist without an admin (for Club-Biz)
# can be followed by students

class Club < ActiveRecord::Base
  belongs_to :admin, class_name: "Admin"
  has_many :student_clubs, foreign_key: "club_id", dependent: :destroy
  has_many :students, through: :student_clubs, source: :student
  has_many :events, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_attached_file :logo, styles: {thumb: "100x100#"}, default_url: "/images/:style/missing.png"
  validates_attachment :logo, presence: true, 
    content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }, 
    size: {in: 0..500.kilobytes}

  validates :name,  presence: true, length: { maximum: 100 }, uniqueness: { case_sensitive: false }
  validates :description,  presence: true, length: { maximum: 500 }
  VALID_URL_REGEX = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*‌​)?$/ix
  validates :website_url, format: { with: VALID_URL_REGEX, multiline: true, allow_blank: true}
  
  
  default_scope -> {order('name ASC')}

  def add_event(e)
  	@event = Event.find(e)
  end

  def add_group(g)
    club_groups.create!(group_id: g.id)
  end


end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :has_admin_acct, only: [:new]
  before_action :signed_in_user, only: [:edit, :update, :index, :show]
  before_action :correct_user, only: [:edit, :update]

  # accessible to any student users
  def index
    if params[:search] and params[:search] != ''
      @clubs = Club.where('name LIKE ?', '%' + params[:search] + '%')
    else
      @clubs = Club.all
    end
  end

  def show
  	@club = Club.find(params[:id])
    @events = @club.events
  end

  def new # those who have completed verification and admin acct process only
    @admin = Admin.find_by(remember_token: params[:remember_token])
    @club = @admin.build_club(admin_id: @admin.id)
  end

  def create
    @admin = Admin.find(params[:club][:admin_id])
    @club = @admin.build_club(club_params)
  	if @club.save
  		flash[:success] = "Club profile created! The registration process is complete."
      sign_in (@admin)
  		redirect_to @club
  	else
  		render 'new'
  	end
  end

  # edit and update accessible to admin user
  def edit 
    @current_user = current_user 
  end

  def update
    @club = current_user.club
  	if @club.update_attributes(club_params)
  		flash[:success] = "Club profile updated"
  		redirect_to @club
  	else
  		render 'edit'
  	end
  end

  private

    def club_params
      params.require(:club).permit(:name, :description, :website_url, :logo)
    end

    def has_admin_acct
      redirect_to new_verification_path, notice: "You must be a club administrator registered with Club-Biz to create a club profile." unless Admin.exists?(remember_token: params[:remember_token])
    end

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @club = Club.find(params[:id])
      @admin = Admin.find_by(id: @club.admin_id) # the correct admin of this club
      redirect_to(root_url) unless current_user?(@admin)
    end

end

app/views/clubs/_follow.html.erb
<%= form_for(current_user.student_clubs.build(club_id: @club.id)) do |f| %>
  <%= f.hidden_field :club_id %>
  <%= f.submit "Follow", class: "btn btn-large btn-primary btn-small" %>
<% end %>

app/views/clubs/_follow_form.html.erb
  <% if student? and current_user.following?(@club) %>
    <%= render 'unfollow' %>
  <% elsif student? %>
    <%= render 'follow' %>
  <% end %>
 

app/views/clubs/_unfollow.html.erb
<%= form_for(current_user.student_clubs.find_by(club_id: @club.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large btn-small" %>
<% end %>

app/views/clubs/edit.html.erb
<% provide(:title, "Edit club profile") %>
<div class="center">
  <%= link_to "Preview profile", club_path %>
</div>

<h1>Edit Club Profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@current_user.club) do |f| %>
      <%= render 'shared/error_messages', object: @current_user.club %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :website_url, 'Website URL' %>
      <%= f.text_field :website_url %>

      <%= f.label :logo, 'Club logo or image' %>
      <%= f.file_field :logo %>
  </div>
  <div class="span6 offset3">
    
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/clubs/index.html.erb
<% provide(:title, 'Browse clubs') %>
<h1>Browse clubs</h1>

<!--search bar -->
<div class = "span5 offset3">
	<%= form_tag clubs_path, method: 'get' do %>
	    <%= text_field_tag :search, params[:search] %>
</div>
<div class = "span1 offset 3">
	    <button type = "submit" class="btn">Search</button>
	<% end %>
</div>

<!--event list -->

<div class = "span6 offset3">
	<ul class="clubs">
	  <% @clubs.each do |club| %>
	    <li>
	      <%= link_to image_tag(club.logo.url(:thumb)), club %>
	      <%= link_to club.name, club %>
		</li>
	  <% end %>
	</ul>
</div>

app/views/clubs/new.html.erb
<% provide(:title, 'Create club profile') %>
<h1>Create club profile</h1>

<div class="row">
  <div class="span6 offset3">
    <div class="center">
      <em>You're almost there. Now create a club profile.</em>
    </div>
    
    <%= form_for(@club) do |f| %>
      <div><%= f.hidden_field :admin_id %></div>
      <%= render 'shared/error_messages', object: @club %>

      <%= f.label :name, 'Club Name' %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :website_url, 'Website URL (optional)' %>
      <%= f.text_field :website_url %>

      <%= f.label :logo, 'Club logo or image' %>
      <%= f.file_field :logo %>
  </div>
  <div class="span6 offset3">
      <%= f.submit "Create club", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/clubs/show.html.erb
<% provide(:title, @club.name) %>
<div class = "span6 offset3">
  <div class="row">
    <section>
      <h1>
        <%= image_tag @club.logo.url(:thumb) %>
        <%= @club.name %>
      </h1>
    </section>

    <section>
      <p>
        <%= @club.description %>
        <br><%= link_to @club.website_url, @club.website_url %>
      </p>
      <%= render 'follow_form'%>
    </section>

    <section>
      <h2>Club Events</h2>
      <% if @events.any? %>
  	    <ul class="clubs">
  	      <% @events.each do |event| %>
  			    <li>
              <%= event.start.strftime("%d %b %y %H:%M") %>
              <%= link_to event.name, event %>
            </li>
  	  		<% end %>
  	    </ul>
      <% else %>
        <em>No events yet.</em>
  	  <% end %>
  </section>
  </div>
</div>