config/routes.rb
ClubBiz::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :students do
    member do
      get :clubs
      get :events
      get :messages
    end
  end
  resources :admins do
    member do
      get :events
      get :details
      get :groups
    end
  end
  resources :clubs
  resources :student_clubs, only: [:create, :destroy]
  resources :events do
    member do
      get :club
      get :ads
      get :announcements
      get :new_reservation
      get :sales
    end
  end
  resources :ticket_reservations, only: :create
  resources :posts, only: :create
  resources :ads, only: :create
  resources :announcements, only: :create
  resources :messages, only: :create
  resources :registered_clubs do
    member do
      get :officers
    end
  end
  resources :officers, only: :create
  resources :verifications, only: [:new, :create, :update]
  resources :admin_details, only: :create

  root 'static_pages#home'
  match '/signup',  to: 'students#new',         via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get 'search_events' => 'events#index'
  get 'search_clubs' => 'clubs#index'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Club-Biz!</h1>
  <% if !signed_in? %>
	  <%= link_to "Sign in", signin_path, class: "btn btn-large btn-primary" %>
	  <%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %>
	</div>
	<div class="center"><%= link_to "Want to sign up as a club? Register your club with Club-Biz", new_verification_path %></div>
  <% end %>