config/routes.rb
ClubBiz::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :students do
    member do
      get :clubs
      get :events
      get :messages
    end
  end
  resources :admins do
    member do
      get :events
      get :details
      get :groups
    end
  end
  resources :clubs
  resources :student_clubs, only: [:create, :destroy]
  resources :events do
    member do
      get :club
      get :ads
      get :announcements
      get :new_reservation
      get :sales
    end
  end
  resources :ticket_reservations, only: :create
  resources :posts, only: :create
  resources :ads, only: :create
  resources :announcements, only: :create
  resources :messages, only: :create
  resources :registered_clubs do
    member do
      get :officers
    end
  end
  resources :officers, only: :create
  resources :verifications, only: [:new, :create, :update]
  resources :admin_details, only: :create

  root 'static_pages#home'
  match '/signup',  to: 'students#new',         via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get 'search_events' => 'events#index'
  get 'search_clubs' => 'clubs#index'
  

end

app/models/event.rb
# main class to store event data incl. basic details and ticket purchase info
# also stores related students, posts, ads, announcements
# an event is associated with one club, and can only be created by an Admin.

class Event < ActiveRecord::Base
  belongs_to :club, class_name: "Club"
  has_many :ticket_reservations, foreign_key: "event_id", dependent: :destroy
  has_many :students, through: :ticket_reservations, source: :student
  has_many :posts, foreign_key: "event_id", dependent: :destroy
  has_many :ads, foreign_key: "event_id", dependent: :destroy
  has_many :announcements, foreign_key: "event_id", dependent: :destroy

  has_attached_file :banner, styles: {thumb: "100x100#"}, default_url: "/images/:style/missing.png"
  validates_attachment :banner, presence: true, 
    content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }, 
    size: {in: 0..1.megabytes}

  validates :name, presence:true
  validates :start, presence:true 
  validates :end, presence:true
  validates :location, presence:true, length: {minimum: 4}
  validates :description, presence:true, length: {maximum: 500}
  validates :ticket_price, presence:true, numericality: :true
  validates :initial_tickets_avail, presence:true, numericality: {only_integer: true}
  validates :ticket_purchase_instructions, presence:true, length: {maximum: 140}
  validates :sales_start, presence:true
  validates :sales_end, presence:true
  validates :conditions, presence:true, length: {maximum: 200}
  validates :banner, presence:true

  validate :valid_start, :valid_end, :valid_sales_start, :valid_sales_end
  validate :start_has_time, :end_has_time, :sales_start_has_time, :sales_end_has_time
  validate :start_in_future, :sales_start_in_future
  validate :end_after_start, :sales_end_after_start

  default_scope -> {order('start ASC')}

  # THE FOLLOWING ARE ALL DATETIME VALIDATIONS #
  def start_has_time
    errors.add(:start, " must have a time. Time cannot be midnight.") unless \
    has_time?(self.start)
  end

  def end_has_time
    errors.add(:end, " must have a time. Time cannot be midnight.") unless \
    has_time?(self.end)
  end

  def sales_start_has_time
    errors.add(:sales_start, " must have a time. Time cannot be midnight.") unless \
    has_time?(self.sales_start)
  end

  def sales_end_has_time
    errors.add(:sales_end, " must have a time. Time cannot be midnight.") unless \
    has_time?(self.sales_end)
  end

  def has_time?(dt)
    dt.strftime("%H:%M") != "00:00"
    rescue NoMethodError
      false 
  end

  def valid_start
    errors.add(:start, " date/time not valid. Please enter in format DD/MM/YYYY HH:MM") unless \
    valid_datetime?(self.start)
  end

  def valid_end
    errors.add(:end, " date/time not valid. Please enter in format DD/MM/YYYY HH:MM") unless \
    valid_datetime?(self.end)
  end

  def valid_sales_start
    errors.add(:sales_start, " date/time not valid. Please enter in format DD/MM/YYYY HH:MM") unless \
    valid_datetime?(self.sales_start)
  end

  def valid_sales_end
    errors.add(:sales_end, " date/time not valid. Please enter in format DD/MM/YYYY HH:MM") unless \
    valid_datetime?(self.sales_end)
  end

  def valid_datetime?(dt)
    str = dt.strftime("%d/%m/%Y %H:%M")
    DateTime.parse(str)
    true
    rescue ArgumentError, NoMethodError
      false
  end

  def start_in_future
    if !self.start.nil?
      errors.add(:start, " cannot be in the past.") unless self.start > DateTime.now
    end
  end

  def sales_start_in_future
    if !self.sales_start.nil?
      errors.add(:sales_start, " cannot be in the past.") unless self.sales_start > DateTime.now
    end
  end

  def end_after_start
    if !self.start.nil? and !self.end.nil?
      errors.add(:end, " cannot be before start") unless self.end > self.start
    end
  end

  def sales_end_after_start
    if !self.sales_start.nil? and !self.sales_end.nil?
    errors.add(:sales_end, " cannot be before start") unless self.sales_end > self.sales_start
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in_user
  before_action :student_user, only: [:new_reservation]
  before_action :not_in_past, only: [:new_reservation]
  before_action :not_already_attending, only: [:new_reservation]
  before_action :correct_admin, only: [:edit, :update, :ads, :announcement, :sales]

  # accessible to students
  def index
    # must filter out past events
    if params[:search] and params[:search] != ''
      @events = Event.where('start > ? AND name LIKE ?', Time.now, '%' + params[:search] + '%')
    else
      @events = Event.where('start > :now', now: Time.now)
    end
  end

  def show
    @event = Event.find(params[:id])
    @post = @event.posts.build(event_id: @event.id)
    @posts = @event.posts.take(@event.posts.size-1) # must slice off the anonymous new post
    @tickets_remaining = tickets_remaining
  end

  def new_reservation # STUDENTS ONLY
    @event = Event.find(params[:id])
    @ticket_reservation = current_user.ticket_reservations.build(event_id: @event.id)
    # must slice off the anonymous reservation
    @ticket_reservations = @event.ticket_reservations.take(@event.ticket_reservations.size-1)
    @tickets_remaining = tickets_remaining
    render 'show_new_reservation'
  end

  # accessible to club admins
  def new
  	@event = Event.new
  end

  def create
  	@event = Event.new(event_params)
  	@event.club_id = current_user.club.id 
  	if @event.save
  	  current_user.club.add_event(@event)
  	  flash[:success] = "Event created."
      redirect_to @event
  	else
  		render 'new'
  	end
    rescue ArgumentError
      flash[:error] = "Error. Please start over."
      @event = Event.new
      render 'new' 
  end

  # admin toolbox 
  def ads
    @event = Event.find(params[:id])
    render 'show_ads'
  end

  def announcements 
    @event = Event.find(params[:id])
    render 'show_announcements'
  end

  def sales
    @event = Event.find(params[:id])
    @reservations = @event.ticket_reservations
    @total_sales = (@event.ticket_price * @reservations.sum(:num_tickets)).to_s
    render 'show_sales'
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted."
    redirect_to events_admin_path ({id: current_user.id})
  end

  private

    def event_params
      params.require(:event).permit(:name, :start, :end,
      	:location, :description, :ticket_price, :initial_tickets_avail, 
        :ticket_purchase_instructions, :sales_start, :sales_end, :conditions, 
        :website_URL, :banner)
    end

    def tickets_purchased?
      !@event.ticket_reservations.empty?
    end

    def tickets_remaining
      if tickets_purchased?
        @event.initial_tickets_avail - @event.ticket_reservations.sum(:num_tickets)
      else
        @event.initial_tickets_avail
      end
    end

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_admin
      @event = Event.find(params[:id])
      @club = Club.find_by(id:@event.club_id)
      @admin = Admin.find_by(id: @club.admin_id) # the correct admin of this event's club
      redirect_to root_url, notice: "Access denied." unless current_user?(@admin)
    end

    def student_user
      redirect_to event_path, notice: "Only student users are permitted to make ticket reservations." unless student?
    end

    def not_already_attending
      @event = Event.find(params[:id])
      redirect_to event_path, notice: "You are already attending the event." if @event.students.exists?(id: current_user.id)
    end

    def not_in_past
      @event = Event.find(params[:id])
      redirect_to event_path, notice: "That event already occurred." if @event.start < Time.now
    end

end

app/views/events/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <div><%= f.hidden_field :event_id %></div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary btn-sm" %>
<% end %>

app/views/events/_posts.html.erb
<% if student? %>
  <div class = "span6 offset3">
<% end %>

  <% if @posts.any? %>
    <p>       
    <% @posts.each do |post| %>
      <ul class = "generic-list">
      	<% if post.user.type == 'Student' %>
  	      <li><b><%= post.user.first_name + ' ' + post.user.last_name%></b></li>
  	    <% elsif post.user.type == 'Admin' %>
  	      <li><b><%= post.user.club.name %></b></li>
  	    <% end %>
  	      <li><%= post.content %></li>
  	      <li><small><em><%= l post.created_at %></em></small></li>
      </ul>
    <% end %>
  <% else %>
    No posts yet.
  <% end %>


<% if student? %>
  </div>
<% end %>

app/views/events/_search_form.html.erb
<!--Search bar for all events.-->
<form class="form-search" action = "/search_events" method="GET">

  <!--Search bar-->
  <div class="nav-bar-header">
  	<input type = "text" name = "search" style="width: 75%"/>
  	<button type = "submit" class="btn">
      Search
  		<span class="icon-bar"></span>
  	</button>
  </div>
  
  <!--checkboxes--> 
  <div class="checkbox">
  	<label>
  		<input type = "checkbox" name = "search_by_name" value="name">Search by <i>event</i><br>
  	</label>
	<label>	
  		<input type = "checkbox" name = "search_by_club" value="club">Search by <i>club</i><br>
  	</label>
  </div>
  
</form>

app/views/events/_tools.html.erb
<div class="center">
	<%= link_to "Edit event", edit_event_path, class: "btn btn-primary btn-small" %></li>
	<%= link_to "Post ad", ads_event_path, class: "btn btn-primary btn-small" %></li>
	<%= link_to "Post announcement", announcements_event_path, class: "btn btn-primary btn-small" %></li>
	<%= link_to "Sales report", sales_event_path, class: "btn btn-primary btn-small" %></li>
	<%= link_to "Delete event", @event, :method => :delete, :data => {confirm: "Are you sure?"}, class: "btn btn-primary btn-small" %></li>
</div>

app/views/events/edit.html.erb
<% provide(:title, 'Edit your event') %>
<h1>Edit your event</h1>

<div class="row">
  <%= form_for(@event) do |f| %>
  <div class="span6 offset3">
    All fields are required unless otherwise stated.
    <%= render 'shared/error_messages', object: @event %>
    
    <h3>Event details</h3>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class = "span3 offset3">
    <%= f.label :start %>
    <%= f.text_field :start, value: @event.start.strftime("%d/%m/%Y %H:%M") %>

    <%= f.label :end %>
    <%= f.text_field :end, value: @event.end.strftime("%d/%m/%Y %H:%M") %>
  </div>


  <div class="span6 offset3">
    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 6 %>
      
    <h3>Ticket purchase information</h3>
  </div>
    
  <div class ="span3 offset3">
    <%= f.label :ticket_price, 'Ticket price $' %>
    <%= f.text_field :ticket_price %>

  </div>

  <div class = "span6 offset3">
    <%= f.label :ticket_purchase_instructions %>
    <%= f.text_area :ticket_purchase_instructions %>
  </div>

  <div class = "span3 offset3">
    <%= f.label :sales_start %>
    <%= f.text_field :sales_start, value: @event.sales_start.strftime("%d/%m/%Y %H:%M") %>

    <%= f.label :sales_end %>
    <%= f.text_field :sales_end, value: @event.sales_end.strftime("%d/%m/%Y %H:%M") %>
  </div>

  <div class="span6 offset3">
    <%= f.label :conditions %>
    <%= f.text_area :conditions, rows: 3 %>

    <h3>Additional Information</h3>

    <%= f.label :banner, 'Banner photo' %>
    <%= f.file_field :banner %>
    </div>

  <div class="span6 offset3">
    <%= f.label :website_URL, 'Website URL(optional)' %>
    <%= f.text_field :website_URL %>

    <%= f.submit "Update event", class: "btn btn-large btn-primary" %>
  </div>
  <% end %>
</div>

app/views/events/index.html.erb
<% provide(:title, 'Browse events') %>
<h1>Browse events</h1>

<!--search bar -->
<div class = "span5 offset3">
	<%= form_tag events_path, method: 'get' do %>
	  <%= text_field_tag :search, params[:search] %>
</div>
<div class = "span1">
	  <button type = "submit" class="btn">Search</button>
	<% end %>
</div>

<!--event list -->
<div class = "span6 offset3">
	<ol class="clubs">
	  <% @events.each do |event| %>
	    <li>
	      <%= link_to image_tag(event.banner.url(:thumb)), event %>
	      <%= event.start.strftime("%d %b %y %H:%M") %> 
	      &nbsp;&nbsp;
	      <%= link_to event.name, event %>     
		</li>
	  <% end %>
	</ol>
</div>

app/views/events/new.html.erb
<% provide(:title, 'Create an event') %>
<h1>Create event</h1>


<div class="row">
  <%= form_for(@event) do |f| %>
  <div class="span6 offset3">
    All fields are required unless otherwise stated.
    <%= render 'shared/error_messages', object: @event %>
    
    <h3>Event details</h3>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class = "span3 offset3">
    <%= f.label :start %>
    <%= f.text_field :start, placeholder: "DD/MM/YYYY HH:MM" %>

    <%= f.label :end %>
    <%= f.text_field :end, placeholder: "DD/MM/YYYY HH:MM" %>
  </div>


  <div class="span6 offset3">
    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 6 %>
      
    <h3>Ticket purchase information</h3>
  </div>
    
  <div class ="span3 offset3">
    <%= f.label :ticket_price, 'Ticket price $' %>
    <%= f.text_field :ticket_price %>

    <%= f.label :initial_tickets_avail %>
    <%= f.text_field :initial_tickets_avail %>
  </div>

  <div class = "span6 offset3">
    <%= f.label :ticket_purchase_instructions %>
    <%= f.text_area :ticket_purchase_instructions %>
  </div>

  <div class = "span3 offset3">
    <%= f.label :sales_start, placeholder: "DD/MM/YYYY HH:MM" %>
    <%= f.text_field :sales_start, placeholder: "DD/MM/YYYY HH:MM" %>

    <%= f.label :sales_end, placeholder: "DD/MM/YYYY HH:MM" %>
    <%= f.text_field :sales_end, placeholder: "DD/MM/YYYY HH:MM" %>
  </div>

  <div class="span6 offset3">
    <%= f.label :conditions %>
    <%= f.text_area :conditions, rows: 3 %>

    <h3>Additional Information</h3>
    <%= f.label :banner, 'Banner photo' %>
    <%= f.file_field :banner %>
  </div>
  
  <div class="span6 offset3">
    <%= f.label :website_URL, 'Website URL(optional)' %>
    <%= f.text_field :website_URL %>

    <%= f.submit "Create event", class: "btn btn-large btn-primary" %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<div class="row">
<div class = "span6 offset3">
  <% if admin? %>
    <%= render 'tools'%>
  <% end %>

  <!--EVENT DESCRIPTION AND INFORMATION -->
  <head>
    <h1>
      <%= @event.name %>
    </h1>
  </head>
  <body>
    <section>
      <div class="center">
        <p>
         <%= image_tag @event.banner.url %>
        </p>
        <ul class="generic-list">
          <li>
            <b>Hosted by </b><%= @event.club.name %>
          </li>
          <li>
            <b>Start: </b><%= @event.start.strftime("%d %b %y at %H:%M") %>
            <b>End: </b><%= @event.end.strftime("%d %b %y at %H:%M") %>
          </li>
          <li>
            <b>Location: </b><%= @event.location %>
          </li>
          <li>
            <b>Ticket price: </b><%= number_to_currency(@event.ticket_price) %>
            <b>Tickets remaining: </b><%= @tickets_remaining %>
          </li>
        </ul>


        <!-- JOIN BUTTON, STUDENTS ONLY, FUTURE ONLY -->
        <% if student? and !current_user.joined?(@event) and @event.start > Time.now %>
          <br>
          <%= link_to 'Join and reserve tickets', 
          new_reservation_event_path, class: "btn btn-primary btn-sm" %>
        <% elsif student? and @event.start > Time.now %>
          <em> You are attending this event. </em>
        <% elsif student? %> 
          <em>This event has already happened.</em>
        <% end %>

    </section>

    <section>
      <h4>Event Description</h4>
      <%= @event.description %>
    </section>

    <!--POST FORM AND POSTS -->
    <section>
      <h4>Posts</h4>
      <% if student? %>
        <%= render 'post_form'%>
        </div>
      <% end %> 

      <%= render 'posts' %>
    </section>

  </body>


</div>
</div>

app/views/events/show_ads.html.erb
<div class = "span6 offset3">
	<% provide(:title, 'Post an ad') %>
	<h3>Create an ad</h3>
	<p><em>This ad will be sent as a message to all of your club followers</em></p>
	<%= form_for(@event.ads.build(event_id: @event.id)) do |f| %>
	  <div><%= f.hidden_field :event_id %></div>
	  <div class="field">
	    <%= f.text_area :content, placeholder: "Write ad copy here...", rows: 6 %>
	  </div>
	  <%= f.submit "Send ad", class: "btn btn-large btn-primary" %>
	<% end %>
</div>

app/views/events/show_announcements.html.erb
<div class = "span6 offset3">
	<% provide(:title, 'Post an ad') %>
	<h3>Post an announcement.</h3>

	<p><em>This announcement will show up in your event's Posts, and 
		be sent as a message to all registered attendees.</em></p>

	<%= form_for(@event.announcements.build(event_id: @event.id)) do |f| %>
	  <div><%= f.hidden_field :event_id %></div>
	  <div class="field">
	    <%= f.text_area :content, placeholder: "Compose announcement...", rows: 4 %>
	  </div>
	  <%= f.submit "Post announcement", class: "btn btn-large btn-primary" %>
	<% end %>
	
</div>

app/views/events/show_new_reservation.html.erb
<div class = "span6 offset3">
  <h1>
    Reserve tickets for <%= @event.name %>
  </h1>
<!-- INSTRUCTIONS AND CONDITIONS -->
  <ul class="generic-list">
    <li><b>Purchase Instructions</b></li>
    <li><em>This form does not complete a ticket purchase transaction. 
      Please follow the instructions as follows.</em></li>
	  <li><%= @event.ticket_purchase_instructions %></li>
    <li><em>Sales start at <%= l @event.sales_start %> </em></li>
    <li><em>Sales end at <%= l @event.sales_end %>.</em></li>
    <li><b>Conditions of Reservation</b></li>
    <li><%= @event.conditions %></li>
    <li><b>Tickets Remaining: </b><%= @tickets_remaining %>
  </ul>
</div>
<!-- RESERVATION FORM -->
<div class="span2 offset3">
  <%= form_for(@ticket_reservation) do |f| %>
    <div><%= f.hidden_field :event_id %></div>
    <%= f.label :num_tickets, 'Number of tickets to reserve' %>
    <%= f.select :num_tickets, (1..20).to_a, selected: @ticket_reservation.num_tickets %>
    <%= f.submit "Reserve tickets", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/events/show_sales.html.erb
<% provide(:title, @title) %>
<div class="span8">
  <h3>Sales Report</h3>
  Total Sales = <%= number_to_currency(@total_sales) %>
  <% if @reservations.any? %>
      <table class = "table">
        <thead>
          <tr>
            <th>Created At</th>
            <th>Booking Made By</th>
            <th>Number of Tickets</th>
          </tr>
        </thead>
        <tbody>
          <% @reservations.each do |reservation| %>
            <tr>
              <td class = "span2"><%= l reservation.created_at %></td>
              <td class = "span4"><%= reservation.student.first_name + ' ' + reservation.student.last_name %></td>
              <td class = "span2"><%= reservation.num_tickets %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
</div>