config/routes.rb
ClubBiz::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :students do
    member do
      get :clubs
      get :events
      get :messages
    end
  end
  resources :admins do
    member do
      get :events
      get :details
      get :groups
    end
  end
  resources :clubs
  resources :student_clubs, only: [:create, :destroy]
  resources :events do
    member do
      get :club
      get :ads
      get :announcements
      get :new_reservation
      get :sales
    end
  end
  resources :ticket_reservations, only: :create
  resources :posts, only: :create
  resources :ads, only: :create
  resources :announcements, only: :create
  resources :messages, only: :create
  resources :registered_clubs do
    member do
      get :officers
    end
  end
  resources :officers, only: :create
  resources :verifications, only: [:new, :create, :update]
  resources :admin_details, only: :create

  root 'static_pages#home'
  match '/signup',  to: 'students#new',         via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get 'search_events' => 'events#index'
  get 'search_clubs' => 'clubs#index'
  

end

app/views/layouts/_admin_header.html.erb
<ul class="nav pull-left">
  <li><%= link_to "Create Event", new_event_path %></li>
  <li><%= link_to "Events", events_admin_path(current_user) %></li>
  <li><%= link_to "Club Profile", edit_club_path(current_user.club) %></li>
</ul>

<ul class="nav pull-right">
  <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
</ul>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "club-biz", root_path, id: "logo" %>
      <nav>
        <% if signed_in? and student? %>
          <%= render 'layouts/student_header' %>

        <% elsif signed_in? and admin? %>
          <%= render 'layouts/admin_header' %>

        <% elsif signed_in? and root? %>
          <ul class="nav pull-right">
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>
          
        <% end %>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_student_header.html.erb
<ul class="nav pull-left">
  <li><%= link_to "Browse Events", events_path %></li>
  <li><%= link_to "Browse Clubs", clubs_path %></li>
</ul>

<ul class="nav pull-right">
  <li><%= link_to "My Events", events_student_path(current_user) %></li>
  <li><%= link_to "My Clubs", clubs_student_path(current_user) %></li>
  <li><%= link_to "Messages", messages_student_path(current_user) %></li>
  <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>